"use client";

import { deleteMuseAction, saveMuseAction } from "@/app/admin/actions";
import { ImageUploader } from "@/components/admin/image-uploader";
import type { Muse } from "@/lib/cms-types";

export function MuseEditor({ muse }: { muse: Muse }) {
  return <form action={saveMuseAction} className="space-y-8"><input type="hidden" name="id" value={muse.id} /><input type="hidden" name="status" value={muse.status} /><section className="admin-panel grid gap-5 md:grid-cols-2"><label className="admin-label md:col-span-2">Title<input name="title" defaultValue={muse.title} required className="admin-input mt-2" /></label><label className="admin-label">Category<input name="category" defaultValue={muse.category} className="admin-input mt-2" placeholder="Book, color, artist, place…" /></label><label className="admin-label">Display order<input type="number" name="display_order" defaultValue={muse.display_order} className="admin-input mt-2" /></label><label className="admin-label md:col-span-2">Why it inspires me<textarea name="note" defaultValue={muse.note} rows={7} className="admin-input mt-2" /></label><label className="admin-label">Source name<input name="source_name" defaultValue={muse.source_name} className="admin-input mt-2" /></label><label className="admin-label">Source link<input type="url" name="source_url" defaultValue={muse.source_url} className="admin-input mt-2" /></label></section><section className="admin-panel"><h2 className="admin-section-title">Images</h2><p className="admin-help">The first image leads the card.</p><div className="mt-5"><ImageUploader initialImages={muse.images} max={4} /></div></section><EditorActions status={muse.status} preview="/muses" deleteAction={deleteMuseAction} label="muse" /></form>;
}

function EditorActions({ status, preview, deleteAction, label }: { status: string; preview: string; deleteAction: (data: FormData) => void; label: string }) { return <div className="sticky bottom-4 z-20 flex flex-wrap gap-3 rounded-2xl border border-olive-900/10 bg-white/95 p-4 shadow-xl"><button name="intent" value="draft" className="admin-button-secondary">Save Draft</button><button name="intent" value="publish" className="admin-button">{status === "published" ? "Save Changes" : "Publish"}</button>{status === "published" ? <button name="intent" value="unpublish" className="admin-button-secondary">Unpublish</button> : null}<a href={preview} target="_blank" className="admin-button-secondary">Preview</a><button formAction={deleteAction} onClick={(event) => { if (!confirm(`Delete this ${label} permanently?`)) event.preventDefault(); }} className="ml-auto text-sm font-semibold text-pimento-700">Delete</button></div>; }
